package com.motionarcade.app.monster

import java.util.Base64

/** Exact bytes emitted by the pre-envelope monster-raid encoder at commit dece589. */
internal object MonsterRaidLegacyCheckpointFixtures {
    val soloPausedV2: ByteArray
        get() = Base64.getDecoder().decode(SOLO_PAUSED_V2_BASE64)

    val dualPausedV2: ByteArray
        get() = Base64.getDecoder().decode(DUAL_PAUSED_V2_BASE64)

    private const val SOLO_PAUSED_V2_BASE64 =
        "TVJBSQAAAAIAAAABABNtb25zdGVyLWxlZ2FjeS1zb2xvAAdNT05TVEVSAARTT0xPABVtb25zdGVyLXJh" +
            "aWQtcnVsZXMtdjEAAAAAAAAARwAMeG9yLWluZGV4LXYxAAAAAQAAAAIAAAAAAAAAAAAGUEFVU0VEAQAO" +
            "QVBQX0JBQ0tHUk9VTkQABFdBVkUAAAAAAAxNT1NTX0NSQVdMRVIAAAAeAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAEsAAAAAIAAlAxAAhWQU5HVUFSRAAAAGQAAABkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG" +
            "Q0VOVEVSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////////////////////wACQUkABlJB" +
            "TkdFUgAAAGQAAABkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGQ0VOVEVSAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAP///////////////////////////////wAAAAA="

    private const val DUAL_PAUSED_V2_BASE64 =
        "TVJBSQAAAAIAAAABABNtb25zdGVyLWxlZ2FjeS1kdWFsAAdNT05TVEVSAAREVUFMABVtb25zdGVyLXJh" +
            "aWQtcnVsZXMtdjEAAAAAAAAASQAMeG9yLWluZGV4LXYxAAAAAQAAAAIAAAAAAAAAAAAGUEFVU0VEAQAO" +
            "QVBQX0JBQ0tHUk9VTkQABFdBVkUAAAAAAAxNT1NTX0NSQVdMRVIAAAAeAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAEsAAAAAIAAlAxAAhWQU5HVUFSRAAAAGQAAABkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG" +
            "Q0VOVEVSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////////////////////wACUDIABlJB" +
            "TkdFUgAAAGQAAABkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGQ0VOVEVSAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAP///////////////////////////////wAAAAA="
}
